core/urls.py
# core/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls')),
    path('', include('apps.home.urls')),
]

apps/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate 
from .models import Profile

class CustomUserCreationForm(forms.ModelForm):
    fullname = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(max_length=150, required=True)
    phone_number = forms.CharField(max_length=15, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, label='Password', required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password', required=True)
    # permission_level = forms.ChoiceField(choices=Profile.PERMISSION_CHOICES, required=True)

    class Meta:
        model = User
        fields = ('fullname', 'email', 'phone_number', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already exists.")
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if Profile.objects.filter(phone_number=phone_number).exists():
            raise ValidationError("Phone number already exists.")
        return phone_number

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            self.add_error('password2', "Passwords do not match.")
        return cleaned_data
        
class CustomAuthenticationForm(forms.Form):
    email = forms.EmailField(label='Email', required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput, required=True)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if user is None:
                raise ValidationError("Invalid email or password.")
        return cleaned_data

apps/templates/accounts/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Login {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
.center-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }
  .card-custom-width {
    max-width: 900px;
    width: 100%;
  }
  .error-message {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 5px;
        font-weight: bold;
      }
</style>
{% endblock stylesheets %}

{% block content %}

<!-- Page content -->
<div class="container center-container">
  <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
          <div class="card bg-secondary shadow border-0 card-custom-width">
              <div class="card-header bg-transparent pb-5">
                  <div class="text-muted text-center mt-2 mb-3">
                      Sign IN
                  </div>
              </div>
              <div class="card-body px-lg-5 py-lg-5">
                <div class="text-muted text-center mt-2 mb-4">
                    <h1 class="text-white">
                        <a target="_blank" class="text-white" href="" style="display: flex; align-items: center; text-decoration: none;">
                            <img src="/static/assets/img/brand/logo.png" alt="Logo" style="height: 40px; margin-right: 10px;">
                            <span style="color: black; font-size: 24px; font-weight: bold;">Dynamic Documentation System</span>
                        </a>
                    </h1>
                </div>
                
                  <div class="error-message">
                      {% if msg %}
                          <p>{{ msg }}</p>
                      {% else %}
                          <p>Add your credentials</p>
                      {% endif %}
                  </div>
                  <form method="POST">
                      {% csrf_token %}
                      <div class="form-group mb-3">
                          <label for="id_username">Email</label>
                          <div class="input-group input-group-alternative">
                              <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                              </div>
                              {{ form.email }}
                          </div>
                      </div>
                      <div class="form-group mb-3">
                          <label for="id_password">Password</label>
                          <div class="input-group input-group-alternative">
                              <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                              </div>
                              {{ form.password }}
                          </div>
                      </div>
                      <div class="custom-control custom-checkbox">
                          <input class="custom-control-input" id="customCheckLogin" type="checkbox">
                          <label class="custom-control-label" for="customCheckLogin">
                              <span class="text-muted">Remember me</span>
                          </label>
                      </div>
                      <div class="text-center">
                          <button type="submit" class="btn btn-primary my-4">Sign in</button>
                      </div>
                  </form>
                  <div class="row mt-3">
                    <div class="col-6">
                        <a href="{% url 'register' %}" class="text-light"><small>Register</small></a>
                    </div>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

{% block stylesheets %}
<style>
.center-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}
.card-custom-width {
    max-width: 700px;
    width: 100%;
}
</style>
{% endblock stylesheets %}

{% block content %}
<div class="container center-container">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12">
            <div class="card bg-secondary shadow border-0 card-custom-width">
                <div class="card-header bg-transparent pb-5">
                    <div class="text-muted text-center mt-2 mb-4">
                        Sign UP
                    </div>
                </div>
                <div class="card-body px-lg-5 py-lg-5">
                    <div class="text-muted text-center mt-2 mb-4">
                        <h1 class="text-white">
                            <a target="_blank" class="text-white" href="" style="display: flex; align-items: center; text-decoration: none;">
                                <img src="/static/assets/img/brand/logo.png" alt="Logo" style="height: 40px; margin-right: 10px;">
                                <span style="color: black; font-size: 24px; font-weight: bold;">Dynamic Documentation System</span>
                            </a>
                        </h1>
                    </div>
                    <div class="text-center text-muted mb-4">
                        {% if msg %}
                            <div class="alert alert-danger">
                                <p>{{ msg }}</p>
                            </div>
                        {% endif %}
                        <!-- {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-success">
                                    <p>{{ message }}</p>
                                </div>
                            {% endfor %}
                        {% endif %} -->
                        {% if not success %}
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <label for="id_fullname">Full Name</label>
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                                        </div>
                                        <input type="text" name="fullname" id="id_fullname" class="form-control" placeholder="Full Name" required>
                                    </div>
                                    <span class="text-error">{{ form.fullname.errors }}</span>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="id_email">Email</label>
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                                        </div>
                                        <input type="email" name="email" id="id_email" class="form-control" placeholder="Email" required>
                                    </div>
                                    <span class="text-error">{{ form.email.errors }}</span>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="id_phone_number">Phone Number</label>
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-mobile-button"></i></span>
                                        </div>
                                        <input type="text" name="phone_number" id="id_phone_number" class="form-control" placeholder="Phone Number" required>
                                    </div>
                                    <span class="text-error">{{ form.phone_number.errors }}</span>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="id_password1">Password</label>
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                        </div>
                                        <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Password" required>
                                    </div>
                                    <span class="text-error">{{ form.password1.errors }}</span>
                                </div>
                                <div class="form-group mb-3">
                                    <label for="id_password2">Confirm Password</label>
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                        </div>
                                        <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Confirm Password" required>
                                    </div>
                                    <span class="text-error">{{ form.password2.errors }}</span>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary mt-4">Create account</button>
                                </div>
                            </form>
                        {% endif %}
                        <div class="row mt-3">
                            <div class="col-3"></div>
                            <div class="col-3">
                                <a href="{% url 'login' %}" class="text-light"><small>Login</small></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascripts %}{% endblock javascripts %}